namespace PacketComs
{
    public enum PacketType
    {
        SSH_MSG_DISCONNECT = 1,
        SSH_MSG_IGNORE = 2,
        SSH_MSG_UNIMPLEMENTED = 3,
        SSH_MSG_DEBUG = 4,
        SSH_MSG_SERVICE_REQUEST = 5,
        SSH_MSG_SERVICE_ACCEPT = 6,

        SSH_MSG_KEXINIT = 20,
        SSH_MSG_NEWKEYS = 21,

        SSH_MSG_KEXDH_INIT = 30,
        SSH_MSG_KEXDH_REPLY = 31,

        SSH_MSG_USERAUTH_REQUEST = 50,
        SSH_MSG_USERAUTH_FAILURE = 51,
        SSH_MSG_USERAUTH_SUCCESS = 52,
        SSH_MSG_USERAUTH_BANNER = 53,

        SSH_MSG_USERAUTH_INFO_REQUEST = 60,
        SSH_MSG_USERAUTH_INFO_RESPONSE = 61,

        SSH_MSG_GLOBAL_REQUEST = 80,
        SSH_MSG_REQUEST_SUCCESS = 81,
        SSH_MSG_REQUEST_FAILURE = 82,

        SSH_MSG_CHANNEL_OPEN = 90,
        SSH_MSG_CHANNEL_OPEN_CONFIRMATION = 91,
        SSH_MSG_CHANNEL_OPEN_FAILURE = 92,
        SSH_MSG_CHANNEL_WINDOW_ADJUST = 93,
        SSH_MSG_CHANNEL_DATA = 94,
        SSH_MSG_CHANNEL_EXTENDED_DATA = 95,
        SSH_MSG_CHANNEL_EOF = 96,
        SSH_MSG_CHANNEL_CLOSE = 97,
        SSH_MSG_CHANNEL_REQUEST = 98,
        SSH_MSG_CHANNEL_SUCCESS = 99,
        SSH_MSG_CHANNEL_FAILURE = 100
    }
}

namespace Routrek.SSHCV1
{
    public enum PacketType
    {
        SSH_MSG_DISCONNECT = 1,
        SSH_SMSG_PUBLIC_KEY = 2,
        SSH_CMSG_SESSION_KEY = 3,
        SSH_CMSG_USER = 4,
        SSH_CMSG_AUTH_RSA = 6,
        SSH_SMSG_AUTH_RSA_CHALLENGE = 7,
        SSH_CMSG_AUTH_RSA_RESPONSE = 8,
        SSH_CMSG_AUTH_PASSWORD = 9,
        SSH_CMSG_REQUEST_PTY = 10,
        SSH_CMSG_WINDOW_SIZE = 11,
        SSH_CMSG_EXEC_SHELL = 12,
        SSH_CMSG_EXEC_CMD = 13,
        SSH_SMSG_SUCCESS = 14,
        SSH_SMSG_FAILURE = 15,
        SSH_CMSG_STDIN_DATA = 16,
        SSH_SMSG_STDOUT_DATA = 17,
        SSH_SMSG_STDERR_DATA = 18,
        SSH_CMSG_EOF = 19,
        SSH_SMSG_EXITSTATUS = 20,
        SSH_MSG_CHANNEL_OPEN_CONFIRMATION = 21,
        SSH_MSG_CHANNEL_OPEN_FAILURE = 22,
        SSH_MSG_CHANNEL_DATA = 23,
        SSH_MSG_CHANNEL_CLOSE = 24,
        SSH_MSG_CHANNEL_CLOSE_CONFIRMATION = 25,
        SSH_CMSG_PORT_FORWARD_REQUEST = 28,
        SSH_MSG_PORT_OPEN = 29,
        SSH_MSG_IGNORE = 32,
        SSH_CMSG_EXIT_CONFIRMATION = 33,
        SSH_MSG_DEBUG = 36
    }
}